const CAMPAIGN_STATUS = {
  DRAFT: 'DRAFT',
  WAITING: 'WAITING',
  RUNNING: 'RUNNING',
  PAUSE: 'PAUSE',
  END: 'END',
};

const SUB_CAMPAIGN = {
  MY_CAMPAIGN: 'my-campaign',
  OTHER_CAMPAIGN: 'other-campaign',
};

const PAGINATION_LIMIT = 6;

const CAMPAIGN_TYPE = {
  CHATBOT_INTENT: 'CHATBOT_INTENT',
  CHATBOT_USECASE: 'CHATBOT_USECASE',
  FAQ: 'FAQ',
  SLU: 'SLU',
  ASR: 'ASR',
};

const CAMPAIGN_ROLE = {
  MANAGER: 'MANAGER',
  CONTRIBUTOR: 'CONTRIBUTOR',
  REVIEWER: 'REVIEWER',
  VIEWER: 'VIEWER',
};

const MAX_ITEMS_SMALL = 5;

export {
  CAMPAIGN_STATUS,
  CAMPAIGN_TYPE,
  SUB_CAMPAIGN,
  PAGINATION_LIMIT,
  MAX_ITEMS_SMALL,
  CAMPAIGN_ROLE,
};
