const CAMPAIGN_STATUS = {
  DRAFT: 'DRAFT',
  WAITING: 'WAITING',
  RUNNING: 'RUNNING',
  PAUSE: 'PAUSE',
  END: 'END',
};

const CAMPAIGN_TYPE = {
  CHATBOT_INTENT: 'CHATBOT_INTENT',
  CHATBOT_USECASE: 'CHATBOT_USECASE',
};

const SUB_CAMPAIGN = {
  MY_CAMPAIGN: 'my-campaign',
  OTHER_CAMPAIGN: 'other-campaign',
};

const PAGINATION_LIMIT = 6;

export { CAMPAIGN_STATUS, CAMPAIGN_TYPE, SUB_CAMPAIGN, PAGINATION_LIMIT };
