export const SOCKET_EVENT = {
  USER_SEND_INFOR: 'USER_SEND_INFOR',
  USER_FIND_PARTNER: 'USER_FIND_PARTNER',
  USER_STOP_FIND_PARTNER: 'USER_STOP_FIND_PARTNER',
  USER_DECLINE_JOIN_ROOM: 'USER_DECLINE_JOIN_ROOM',
  USER_ACCEPT_JOIN_ROOM: 'USER_ACCEPT_JOIN_ROOM',
  SERVER_SEND_CONFIRM_PROMPT: 'SERVER_SEND_CONFIRM_PROMPT',
  SERVER_SEND_WAITING_PARTNER_CONFIRM: 'SERVER_SEND_WAITING_PARTNER_CONFIRM',
  SERVER_SEND_ROOM_INFO: 'SERVER_SEND_ROOM_INFO',
  SERVER_SEND_USER_DECLINE_JOIN_ROOM: 'SERVER_SEND_USER_DECLINE_JOIN_ROOM',
  SERVER_SEND_USER_CONNECTED: 'SERVER_SEND_USER_CONNECTED',
  USER_SEND_MESSAGE: 'USER_SEND_MESSAGE',
  USER_LEAVE_ROOM: 'USER_LEAVE_ROOM',
  USER_DISCONNECT: 'USER_DISCONNECT',
  SERVER_SEND_MESSAGE_FROM_USER: 'SERVER_SEND_MESSAGE_FROM_USER',
  SERVER_SEND_CONFIRM_INTENT_MSG: 'SERVER_SEND_CONFIRM_INTENT_MSG',
  SERVER_SEND_CONFIRM_SLOT_MSG: 'SERVER_SEND_CONFIRM_SLOT_MSG',
  USER_CONFIRM_INTENT_MSG: 'USER_CONFIRM_INTENT_MSG',
  USER_CONFIRM_SLOT_MSG: 'USER_CONFIRM_SLOT_MSG',
  SERVER_SEND_REMOVE_CURRENT_MSG: 'SERVER_SEND_REMOVE_CURRENT_MSG',
  SERVER_SEND_UPDATE_SLOTS_MAIN_INTENT: 'SERVER_SEND_UPDATE_SLOTS_MAIN_INTENT',
  SERVER_SEND_UPDATE_SLOTS_OTHER_INTENT:
    'SERVER_SEND_UPDATE_SLOTS_OTHER_INTENT',
  SERVER_SEND_ADD_OTHER_INTENT: 'SERVER_SEND_ADD_OTHER_INTENT',
  SERVER_SEND_MISSION_COMPLETE: 'SERVER_SEND_MISSION_COMPLETE',
  SERVER_SEND_MESSAGE_CONFIRM_COMPLETE: 'SERVER_SEND_MESSAGE_CONFIRM_COMPLETE',
};

export const USER_STATUS = {
  CONNECTED: '[OUTSIDE_ROOM][CONNECTED]',
  NOTHING: '[OUTSIDE_ROOM][NOTHING]',
  FINDING_PARTNER: '[OUTSIDE_ROOM][FINDING_PARTNER]',
  WAITING_PARTNER_CONFIRM: '[OUTSIDE_ROOM][WAITING_PARTNER_CONFIRM]',
  CONFIRM_JOIN_ROOM: '[OUTSIDE_ROOM][CONFIRM_JOIN_ROOM]',
  PARTNER_DECLINE_CONFIRM: '[OUTSIDE_ROOM][PARTNER_DECLINE_CONFIRM]',
  IN_ROOM: '[INSIDE_ROOM][IN_ROOM]',
  USER_TYPING: '[INSIDE_ROOM][TYPING]',
  WAITING_CONFIRM_MESSAGE: '[INSIDE_ROOM][WAITING_CONFIRM_MESSAGE]',
  CONFIRM_INTENT_NEW_MESSAGE:
    '[INSIDE_ROOM][CONFIRM_MSG][CONFIRM_INTENT_NEW_MESSAGE]',
  CONFIRM_SLOT_NEW_MESSAGE:
    '[INSIDE_ROOM][CONFIRM_MSG][CONFIRM_SLOT_NEW_MESSAGE]',
  WAITING_CONFIRM_INTENT_NEW_MESSAGE:
    '[INSIDE_ROOM][CONFIRM_MSG][WAITING_CONFIRM_INTENT_NEW_MESSAGE]',
  WAITING_CONFIRM_SLOT_NEW_MESSAGE:
    '[INSIDE_ROOM][CONFIRM_MSG][WAITING_CONFIRM_SLOT_NEW_MESSAGE]',
  MISSION_COMPLETE: '[INSIDE_ROOM][MISSION_COMPLETE]',
  OUTSIDE_ROOM_SERVER_HANDLING: '[OUTSIDE_ROOM][SERVER_HANDLING]',
  INSIDE_ROOM_SERVER_HANDLING: '[INSIDE_ROOM][SERVER_HANDLING]',
};

export const USER_ROLE = {
  CLIENT: 'CLIENT',
  AGENT: 'AGENT',
};

export const LIMIT_CONFIRM_TIME = 10;
