export const SOCKET_EVENT = {
  USER_SEND_INFOR: 'USER_SEND_INFOR',
  USER_FIND_PARTNER: 'USER_FIND_PARTNER',
  USER_STOP_FIND_PARTNER: 'USER_STOP_FIND_PARTNER',
  USER_DECLINE_JOIN_ROOM: 'USER_DECLINE_JOIN_ROOM',
  USER_ACCEPT_JOIN_ROOM: 'USER_ACCEPT_JOIN_ROOM',
  SERVER_SEND_CONFIRM_PROMPT: 'SERVER_SEND_CONFIRM_PROMPT',
  SERVER_SEND_WAITING_PARTNER_CONFIRM: 'SERVER_SEND_WAITING_PARTNER_CONFIRM',
  SERVER_SEND_ROOM_INFO: 'SERVER_SEND_ROOM_INFO',
  SERVER_SEND_USER_DECLINE_JOIN_ROOM: 'SERVER_SEND_USER_DECLINE_JOIN_ROOM',
  SERVER_SEND_USER_CONNECTED: 'SERVER_SEND_USER_CONNECTED',
};

export const USER_STATUS = {
  CONNECTED: '[OUTSIDE_ROOM][CONNECTED]',
  NOTHING: '[OUTSIDE_ROOM][NOTHING]',
  FINDING_PARTNER: '[OUTSIDE_ROOM][FINDING_PARTNER]',
  WAITING_PARTNER_CONFIRM: '[OUTSIDE_ROOM][WAITING_PARTNER_CONFIRM]',
  CONFIRM_JOIN_ROOM: '[OUTSIDE_ROOM][CONFIRM_JOIN_ROOM]',
  PARTNER_DECLINE_CONFIRM: '[OUTSIDE_ROOM][PARTNER_DECLINE_CONFIRM]',
  IN_ROOM: '[INSIDE_ROOM][IN_ROOM]',
};

export const USER_ROLE = {
  CLIENT: 'CLIENT',
  AGENT: 'AGENT',
};

export const LIMIT_CONFIRM_TIME = 10;
